telegram_bot/api/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from .views import TelegramUserViewSet, get_qrcode


router = SimpleRouter()

router.register(r'tgm', TelegramUserViewSet)



urlpatterns = [
    path('', include(router.urls)),
    path('product/<id>/download_qrcode', get_qrcode, name='qrcode')

]

telegram_bot/product/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, comments, comment_detail

app_name = 'product'

urlpatterns = [
    path('', index, name='index'),
    path('comments', comments, name='comments'),
    path('comments/<id>', comment_detail , name='comment_detail'),
]

telegram_bot/telegram_bot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('api/', include('api.urls')),
]

telegram_bot/api/models.py
from django.db import models

# Create your models here.

telegram_bot/product/models.py
from django.db import models


import uuid

from django.db import models

from django.dispatch import receiver

from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.files.uploadedfile import InMemoryUploadedFile

from django.conf import settings

import qrcode
from io import BytesIO



from .managers import CommentManager

from tgm.models import TelegramUser




class Marketplace(models.Model):
    """ Таблица маркеплейсов"""

    name = models.CharField(
        max_length=30
    )

    class Meta:
        verbose_name = 'Маркетплейс'
        verbose_name_plural = 'Маркетплейсы'

    def __str__(self):
        return self.name

class Product(models.Model):
    """Таблица товаров"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    name = models.CharField(
        max_length=30
    )
    qrcode = models.ImageField(
        upload_to='qrcode',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

@receiver(models.signals.post_save, sender=Product)
def generate_qrcode(sender, instance, created, *args, **kwargs):
    """Создает qrcode и сохраняет его в оперативной памяти
    после сохраняет на сервер.
    Функция отрабатывает при создании файла"""

    if created:
        url = settings.T_BOT_URL + str(instance.id)
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=6,
            border=0,
        )
        qr.add_data(url)
        qr.make(fit=True)

        img = qr.make_image()
        buffer = BytesIO()
        img.save(buffer)
        filename = f'{instance.name}_{instance.id}.png'
        filebuffer = InMemoryUploadedFile(
            buffer,
            None,
            filename,
            'image/png',
            None,
            None,
        )
        instance.qrcode.save(filename, filebuffer)
        instance.save()


class ProductMarketplace(models.Model):
    """Таблица ссылок товара на маркетплейсах."""

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )
    marketplace = models.ForeignKey(
        Marketplace,
        on_delete=models.CASCADE
    )
    url = models.TextField()

    def __str__(self):
        return f'{self.product} - {self.marketplace}'

class Score(models.Model):
    score = models.PositiveIntegerField(
        unique=True,
        validators=[MinValueValidator(1), MaxValueValidator(10)]
    )
    mid_score = models.BooleanField(
        default=False
    )

    class Meta:
        ordering = ['score',]
        verbose_name = 'Оценка'
        verbose_name_plural = 'Оценки'

    def __str__(self):
        return f'{self.score}'

class CommentProduct(models.Model):
    """
    Таблица с коментариями пользователей о товареы
    """
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )
    user_telegram = models.ForeignKey(
        TelegramUser,
        on_delete=models.CASCADE
    )
    user_score =  models.ForeignKey(
        Score,
        on_delete=models.SET_NULL,
        null=True,
    )
    comment = models.TextField(
        null=True,
        blank=True
    )

    status = models.BooleanField(
        default=False
    )
    date_create = models.DateTimeField(
        auto_now=True
    )
    objects = models.Manager()  # Стандартный менеджер
    scores = CommentManager()  # Менеджер фильтрует данные по оценкам от 1 до 3

    class Meta:
        ordering = ['-date_create']

    def __str__(self):
        return f'{self.user_telegram} - {self.product} - {self.user_score}'

telegram_bot/tgm/models.py
from django.db import models

class TelegramUser(models.Model):
    username = models.CharField(
        max_length=32,
        null=False,
        unique=True
    )
    first_name = models.CharField(
        max_length=64,
        null=False
    )
    last_name = models.CharField(
        max_length=64,
        null=False
    )
    telegram_id = models.PositiveBigIntegerField(
        null=False,
        unique=True
    )

    def __str__(self):
        return f'{self.telegram_id} - {self.username}'

telegram_bot/user/models.py
from django.db import models

from django.contrib.auth import get_user_model


User = get_user_model()

telegram_bot/api/views.py
import os
import mimetypes

from django.shortcuts import render
from rest_framework import viewsets

from wsgiref.util import FileWrapper

from django.http import FileResponse


from django.http import HttpResponse, Http404


from django.conf import settings

from .serializers import UserSerializer, TelegramUserSerializer

from product.models import Product
from user.models import User
from tgm.models import TelegramUser

class TelegramUserViewSet(viewsets.ModelViewSet):
    queryset = TelegramUser.objects.all()
    serializer_class = TelegramUserSerializer



class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer



def get_qrcode(request, id):
    """Скачивание QRCODE."""

    product = Product.objects.get(id=id)
    full_path = os.path.join(settings.MEDIA_ROOT, str(product.qrcode))
    with open(full_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type='image/png')
            response['Content-Disposition'] = f'attachment; filename={os.path.basename(full_path)}'
            return response
    raise Http404

telegram_bot/product/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.conf import settings

from .models import CommentProduct, Score


def index(request):
    return render(request, 'index.html',)

def comments(request):
    comments_list =  CommentProduct.scores.all()
    paginator = Paginator(comments_list, settings.ELEMENT_IN_PAGE)
    page_number = request.GET.get('page', 1)
    comments = paginator.page(page_number)
    context = {
        'page_obj': comments,
    }
    return render(request, 'product/comment.html', context)

def comment_detail(request, id):
    comment = CommentProduct.objects.get(id=id)
    context = {
        'comment': comment
    }
    return render(request, 'product/comment_detail.html', context)

def scores(request):
    scores = Score.objects.all()
    context = {
        'page_obj': scores
    }
    return render(request,)

telegram_bot/tgm/views.py
from django.shortcuts import render

# Create your views here.

telegram_bot/user/views.py
from django.shortcuts import render





def create_user(request):
    """Создать нового пользователя"""

    pass


def change_password(request):
    """Изменить пароль пользователя"""

    pass


def delete_user(requset):
    """Удалить пользователя"""
    pass

telegram_bot/templates/base.html
{% load static %}

<!--Страница-->
<!doctype html>
<html>
    <!--Голова страницы-->
    <head>
        <!--Титул страницы -->
        <meta charset="utf-8">
        <link type="text/css" rel="stylesheet" href="{% static 'base.css' %}"/>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <!--Стили страницы-->
        

    </head>
    <!--Тело страницы-->
    <body>
        <!--Меню пользователя-->
        <div class="header">
            <ul>
                {% if user.is_authenticated %}
                <li>{{ user.username }}</li>
                <li>Выход</li>
                {% else %}
                <li>Вход</li>
                {% endif %}
            </ul>
        </div>
        

        <div class="menu">
            <ul>
                <li><a href="{% url 'product:index' %}">Главная</a></li>
                <li><a href="{% url 'product:comments' %}">Отзывы</a></li>
                <li><a href="">Создать товар</a></li>
                <li>Рассылка</li>
                <li>Маркетплейсы</li>
                <li>Оценки</li>
                <br>
                {% if user.is_superuser %}
                <li>Пользователи</li>
                <li>Создать пользователя</li>
                <li>Оценки</li>
                {%endif%}
            </ul>
        </div>

        <div class="main">
            {% block content %}
            {% endblock %}
        </div>


        <div id="footer">
            {% include "includes/paginator.html"%}
        </div>

    </body>
</html>

telegram_bot/templates/base_test.html
<!--Страница-->
<!doctype html>
<html>
    <!--Голова страницы-->
    <head>
        <!--Титул страницы -->
        <meta charset="utf-8">
        <link type="text/css" rel="stylesheet" href="base.css"/>
        <title>
            title
        </title>
        <!--Стили страницы-->
        

    </head>
    <!--Тело страницы-->
    <body>
        <!--Меню пользователя-->
        <div id="header">
            <ul>
                <li>Вход</li>
                <li>Выход</li>
                <li>User</li>
            </ul>
        </div>
        

        <div class="menu">
            <ul>
                <li>Отзывы</li>
                <li>Создать товар</li>
                <li>Рассылка</li>
                <li>Маркетплейсы</li>
                <li>Оценки</li>
            </ul>
        </div>

        <div id="main">
            <p>body</p>
        </div>


        <div id="footer">
            <p>footer</p>
        </div>

    </body>
</html>

telegram_bot/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
    {% endif %}
    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
    {% endif %}
{% endif %}

telegram_bot/templates/index.html
{% extends  'base.html' %}
{% load static %}

{% block title %}
Главная траница
{% endblock %}

{% block content %}
<h2>Домашняя страница</h2>
{% endblock %}

telegram_bot/templates/product/comment.html
{% extends  'base.html' %}
{% load static %}


{% block title %}
Отзывы
{% endblock %}
{% block content %}
<h2>Отзывы</h2>
<table>
    <thead>
        <tr>
            <th>Product</th>
            <th>User</th>
            <th>Score</th>
            <th>Comment</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for comment in page_obj %}
        <tr>
            <th>{{ comment.product }}</th>
            <th>{{ comment.user_telegram.username }}</th>
            <th>{{ comment.user_score}}</th>
            <th>{{ comment.comment }}</th>
            <th>{{ comment.status }}</th>
            <th><a href="{% url 'product:comment_detail' comment.id %}">Подробнее</a></th>
        </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock %}

        

telegram_bot/templates/product/comment_detail.html
{% extends  'base.html' %}
{% load static %}


{% block title %}
Отзыв
{% endblock %}

{% block content %}

<p>{{ comment.product }}</p>
<p>{{ comment.user_telegram.username }}</p>
<p>{{ comment.user_score }}</p>
<p>{{ comment.comment }}</p>


{% endblock %}